name: "Sample React CI Pipeline / Workflow"

on:
    push:
        branches:
            - main
            - master

jobs:
    build-and-test:
        runs-on: ubuntu-lastest 
        
        steps:
            - name: "Setup node JS"
              uses: actions/setup-node@v4
              with:
                node-version: '21'

            - name: node --version
              run: node --version




